Este conjunto de datos contiene detalles de los clientes de un banco y la variable objetivo es una variable binaria que refleja el hecho de si el cliente dejó el banco (cerró su cuenta) o si continúa siendo un cliente.

VARIABLES QUE CONTIENE EL DATASET

CreditScore: el rango de puntaje crediticio es de 350 a 850.

Geography: el banco regional tiene clientes de tres países: Francia, Alemania y España.

Age: el rango de edad del cliente es de 18 a 92.

Tenure:años que el cliente ha permanecido en el banco.

Balance: la cantidad de dinero disponible para retirar.

NumOfProducts: número de productos que los clientes utilizan en el banco.

IsActiveMember: 1 indica que está activo.

EstimatedSalary: el salario anual informado por el cliente.

Exited: 1 si el cliente cerró cuenta en el banco y 0 si el cliente es retenido

FUENTE: https://www.kaggle.com/shrutimechlearn/churn-modelling

# **PROCEDIMIENTO COMPLETO DE CLASIFICACIÓN**

#01 Lectura de datos

In [4]:
!python --version

Python 3.11.2

In [5]:
# Cómo importar las librerías
import numpy as np
#import matplotlib.pyplot as plt
import pandas as pd

In [6]:
import numpy as np
import pandas as pd
datos= pd.read_csv("E:/OAZ/INEI CURSOS2025 ACT/ENEI 2026 actualizado/04 ML EN PRODUCCION/G1/04 Clasificacion_caso/Churn_Modelling (1).csv", sep = ',')
datos

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

### dataset=datos.copy()

In [7]:
dataset=datos.copy()

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

#**02. Analizar el target**

## dataset tiene los datos originales

#06 Transformaciones de datos


output
Index(['Age', 'Balance', 'NumOfProducts', 'IsActiveMember',
       'Geography_Germany'],
      dtype='object')

In [9]:
datos # Base de datos original

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

##06.1 Selección por RFA

### dataf con el filtro del RFA

In [10]:
# RFA                                                                             Target
dataf=datos[[ "Geography", 'Age',  'Balance', 'NumOfProducts', 'IsActiveMember' ,  'Exited' ]]
dataf

     Geography  Age    Balance  NumOfProducts  IsActiveMember  Exited
0       France   42       0.00              1               1       1
1        Spain   41   83807.86              1               1       0
2       France   42  159660.80              3               0       1
3       France   39       0.00              2               0       0
4        Spain   43  125510.82              1               1       0
...        ...  ...        ...            ...             ...     ...
9995    France   39       0.00              2               0       0
9996    France   35   57369.61              1               1       0
9997    France   36       0.00              1               1       1
9998   Germany   42   75075.31              2               0       1
9999    France   28  130142.79              1               0       0

[10000 rows x 6 columns]

###dataff=dataf.copy()

In [11]:
dataff=dataf.copy()
dataff

     Geography  Age    Balance  NumOfProducts  IsActiveMember  Exited
0       France   42       0.00              1               1       1
1        Spain   41   83807.86              1               1       0
2       France   42  159660.80              3               0       1
3       France   39       0.00              2               0       0
4        Spain   43  125510.82              1               1       0
...        ...  ...        ...            ...             ...     ...
9995    France   39       0.00              2               0       0
9996    France   35   57369.61              1               1       0
9997    France   36       0.00              1               1       1
9998   Germany   42   75075.31              2               0       1
9999    France   28  130142.79              1               0       0

[10000 rows x 6 columns]

#Hemos realizado este proceso porque queremos que el pipeline guarde el procesado para cualitativas y cuantitativas

In [12]:
import os
import math as mt
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt
#import seaborn as sns
import sklearn.model_selection as model_selection
from sklearn.model_selection import RepeatedStratifiedKFold
##from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.compose import make_column_selector
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.base import TransformerMixin

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, roc_auc_score
import joblib

### datosfinal = dataff

In [14]:
# Seleccionar características
datosfinal = dataff[["Geography", 'Age', 'Balance', 'NumOfProducts', 'IsActiveMember', 'Exited']]
datosfinal.head(5)

  Geography  Age    Balance  NumOfProducts  IsActiveMember  Exited
0    France   42       0.00              1               1       1
1     Spain   41   83807.86              1               1       0
2    France   42  159660.80              3               0       1
3    France   39       0.00              2               0       0
4     Spain   43  125510.82              1               1       0

##Data train y test

###datosfinal para Train y Test

In [15]:
X_train, X_test, y_train, y_test= model_selection.train_test_split(
    datosfinal.drop('Exited', axis = 'columns'),           ## TARGET
    datosfinal['Exited'],                                  ## TARGET
    test_size=0.2,
    random_state=123,
    stratify= datosfinal['Exited'])                         ## TARGET

## Pre Procesamiento de datos

In [16]:
# Dividir las variables en categóricas y numéricas
categorical_columns = ["Geography", 'IsActiveMember']  # No debes colocar el Target aquí

numerical_columns = ['Age', 'Balance', 'NumOfProducts']

In [17]:
#num_bins = 5
#from sklearn.preprocessing import OneHotEncoder, StandardScaler, KBinsDiscretizer
prep = ColumnTransformer([('encoder', OneHotEncoder(), categorical_columns),
                          #('discretizer', KBinsDiscretizer(n_bins=num_bins, encode='ordinal', strategy='uniform'), numerical_columns)
                           ('scaler', StandardScaler(),numerical_columns),],
                          remainder= 'drop')

remainder='drop' significa que cualquier columna que no esté asignada explícitamente a un transformador (en este caso, las columnas que no son categóricas ni numéricas) será eliminada del conjunto de datos transformado.

##**Otras opciones para num y cat**

-------------------------------------------------------------------------------
**n_bins**: Especifica el número de bins o intervalos en los cuales se dividirá la variable numérica. En tu caso, n_bins=5 significa que la variable numérica se dividirá en 5 intervalos.

(('discretizer', KBinsDiscretizer(...), numerical_columns)) utiliza KBinsDiscretizer para discretizar las columnas numéricas.

--------------------------------------------------------------------------------

**from sklearn.preprocessing import MinMaxScaler**

**('num', MinMaxScaler(), numeric_features)**   

Escala los datos numéricos en un rango específico (por defecto, entre 0 y 1).
Útil cuando las características numéricas tienen distribuciones no normales

-------------------------------------------------------------------------------

**from sklearn.preprocessing import RobustScaler**

**('num', RobustScaler(), numeric_features)**

Escala los datos utilizando estadísticas robustas para manejar outliers. Útil cuando tus datos numéricos contienen valores atípicos.

------------------------------------------------------------------------------
**from sklearn.preprocessing import OrdinalEncoder**

**('cat', OrdinalEncoder(), categorical_features)**

Útil cuando las variables categóricas tienen un orden intrínseco.Útil cuando las variables categóricas tienen un orden intrínseco. Revisar: https://bait509-ubc.github.io/BAIT509/lectures/lecture5.html

## Opciones para preprocessors

In [18]:
# Crear el preprocesador para no estandarizar datos
preprocessor2 = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_columns),  # 'passthrough' indica que no se aplica ninguna transformación a las numéricas
     #    ('cat', OneHotEncoder(), categorical_features)
    ])

In [19]:
preprocessor3 = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_columns),
     #    ('cat', OneHotEncoder(), categorical_features)
    ],
    remainder='passthrough'
)

# as columnas que no son 'num' ni 'cat' se conservarán en el conjunto de datos preprocesado.
#  Esto puede ser útil si tienes características adicionales que no requieren transformación.

In [20]:
preprocessor4 = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_columns),
     #    ('cat', OneHotEncoder(), categorical_features)
    ],
    remainder='drop'
)
#En este caso, solo las columnas especificadas en las transformaciones 'num' y 'cat' se incluirán en el conjunto de datos preprocesado,
# y las demás se eliminarán

##Validación Cruzada

In [21]:
cv= RepeatedStratifiedKFold(n_splits=5, n_repeats=2, random_state=123)
cv

RepeatedStratifiedKFold(n_repeats=2, n_splits=5, random_state=123)

##PROCESO

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
rf_pipe = Pipeline([('preproc', prep),
                      ('rf', RandomForestClassifier(criterion= 'gini',
                                                    class_weight= 'balanced', random_state=123)  )
                  ])

**class_weight**

aparte de 'balanced', hay otras opciones que puedes utilizar para el parámetro class_weight en el clasificador SVM (Support Vector Machine) con kernel RBF ('rbf') en scikit-learn. Algunas de las opciones comunes incluyen:

None: No se aplica ponderación de clases. Todas las clases tienen el mismo peso.

'balanced' (equilibrado): Como ya mencionaste, este ajusta automáticamente los pesos de las clases inversamente proporcionales a sus frecuencias en los datos de entrenamiento.

dict: Puedes proporcionar un diccionario que asigna pesos específicos a cada clase. Por ejemplo, class_weight={0: 1, 1: 2} asignaría un peso de 1 a la clase 0 y un peso de 2 a la clase 1.

'balanced_subsample': Similar a 'balanced', pero utiliza un subconjunto de datos de entrenamiento para calcular los pesos de clase. Puede ser útil en conjuntos de datos grandes.

In [24]:
rf_pipe.get_params().keys()

dict_keys(['memory', 'steps', 'transform_input', 'verbose', 'preproc', 'rf', 'preproc__force_int_remainder_cols', 'preproc__n_jobs', 'preproc__remainder', 'preproc__sparse_threshold', 'preproc__transformer_weights', 'preproc__transformers', 'preproc__verbose', 'preproc__verbose_feature_names_out', 'preproc__encoder', 'preproc__scaler', 'preproc__encoder__categories', 'preproc__encoder__drop', 'preproc__encoder__dtype', 'preproc__encoder__feature_name_combiner', 'preproc__encoder__handle_unknown', 'preproc__encoder__max_categories', 'preproc__encoder__min_frequency', 'preproc__encoder__sparse_output', 'preproc__scaler__copy', 'preproc__scaler__with_mean', 'preproc__scaler__with_std', 'rf__bootstrap', 'rf__ccp_alpha', 'rf__class_weight', 'rf__criterion', 'rf__max_depth', 'rf__max_features', 'rf__max_leaf_nodes', 'rf__max_samples', 'rf__min_impurity_decrease', 'rf__min_samples_leaf', 'rf__min_samples_split', 'rf__min_weight_fraction_leaf', 'rf__monotonic_cst', 'rf__n_estimators', 'rf__n_jobs', 'rf__oob_score', 'rf__random_state', 'rf__verbose', 'rf__warm_start'])

In [25]:
help(RandomForestClassifier)

Help on class RandomForestClassifier in module sklearn.ensemble._forest:

class RandomForestClassifier(ForestClassifier)
 |  RandomForestClassifier(n_estimators=100, *, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='sqrt', max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None, monotonic_cst=None)
 |
 |  A random forest classifier.
 |
 |  A random forest is a meta estimator that fits a number of decision tree
 |  classifiers on various sub-samples of the dataset and uses averaging to
 |  improve the predictive accuracy and control over-fitting.
 |  Trees in the forest use the best split strategy, i.e. equivalent to passing
 |  `splitter="best"` to the underlying :class:`~sklearn.tree.DecisionTreeClassifier`.
 |  The sub-sample size is controlled with the `max_samples` parameter if
 |  `bootstrap=True` (default), otherwise the whole dataset is used to build
 |  each tree.
 |
 |  For a comparison between tree-based ensemble models see the example
 |  :ref:`sphx_glr_auto_examples_ensemble_plot_forest_hist_grad_boosting_comparison.py`.
 |
 |  This estimator has native support for missing values (NaNs). During training,
 |  the tree grower learns at each split point whether samples with missing values
 |  should go to the left or right child, based on the potential gain. When predicting,
 |  samples with missing values are assigned to the left or right child consequently.
 |  If no missing values were encountered for a given feature during training, then
 |  samples with missing values are mapped to whichever child has the most samples.
 |
 |  Read more in the :ref:`User Guide <forest>`.
 |
 |  Parameters
 |  ----------
 |  n_estimators : int, default=100
 |      The number of trees in the forest.
 |
 |      .. versionchanged:: 0.22
 |         The default value of ``n_estimators`` changed from 10 to 100
 |         in 0.22.
 |
 |  criterion : {"gini", "entropy", "log_loss"}, default="gini"
 |      The function to measure the quality of a split. Supported criteria are
 |      "gini" for the Gini impurity and "log_loss" and "entropy" both for the
 |      Shannon information gain, see :ref:`tree_mathematical_formulation`.
 |      Note: This parameter is tree-specific.
 |
 |  max_depth : int, default=None
 |      The maximum depth of the tree. If None, then nodes are expanded until
 |      all leaves are pure or until all leaves contain less than
 |      min_samples_split samples.
 |
 |  min_samples_split : int or float, default=2
 |      The minimum number of samples required to split an internal node:
 |
 |      - If int, then consider `min_samples_split` as the minimum number.
 |      - If float, then `min_samples_split` is a fraction and
 |        `ceil(min_samples_split * n_samples)` are the minimum
 |        number of samples for each split.
 |
 |      .. versionchanged:: 0.18
 |         Added float values for fractions.
 |
 |  min_samples_leaf : int or float, default=1
 |      The minimum number of samples required to be at a leaf node.
 |      A split point at any depth will only be considered if it leaves at
 |      least ``min_samples_leaf`` training samples in each of the left and
 |      right branches.  This may have the effect of smoothing the model,
 |      especially in regression.
 |
 |      - If int, then consider `min_samples_leaf` as the minimum number.
 |      - If float, then `min_samples_leaf` is a fraction and
 |        `ceil(min_samples_leaf * n_samples)` are the minimum
 |        number of samples for each node.
 |
 |      .. versionchanged:: 0.18
 |         Added float values for fractions.
 |
 |  min_weight_fraction_leaf : float, default=0.0
 |      The minimum weighted fraction of the sum total of weights (of all
 |      the input samples) required to be at a leaf node. Samples have
 |      equal weight when sample_weight is not provided.
 |
 |  max_features : {"sqrt", "log2", None}, int or float, default="sqrt"
 |      The number of features to consider when looking for the best split:
 |
 |      - If int, then consider `max_features` features at each split.
 |      - If float, then `max_features` is a fraction and
 |        `max(1, int(max_features * n_features_in_))` features are considered at each
 |        split.
 |      - If "sqrt", then `max_features=sqrt(n_features)`.
 |      - If "log2", then `max_features=log2(n_features)`.
 |      - If None, then `max_features=n_features`.
 |
 |      .. versionchanged:: 1.1
 |          The default of `max_features` changed from `"auto"` to `"sqrt"`.
 |
 |      Note: the search for a split does not stop until at least one
 |      valid partition of the node samples is found, even if it requires to
 |      effectively inspect more than ``max_features`` features.
 |
 |  max_leaf_nodes : int, default=None
 |      Grow trees with ``max_leaf_nodes`` in best-first fashion.
 |      Best nodes are defined as relative reduction in impurity.
 |      If None then unlimited number of leaf nodes.
 |
 |  min_impurity_decrease : float, default=0.0
 |      A node will be split if this split induces a decrease of the impurity
 |      greater than or equal to this value.
 |
 |      The weighted impurity decrease equation is the following::
 |
 |          N_t / N * (impurity - N_t_R / N_t * right_impurity
 |                              - N_t_L / N_t * left_impurity)
 |
 |      where ``N`` is the total number of samples, ``N_t`` is the number of
 |      samples at the current node, ``N_t_L`` is the number of samples in the
 |      left child, and ``N_t_R`` is the number of samples in the right child.
 |
 |      ``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,
 |      if ``sample_weight`` is passed.
 |
 |      .. versionadded:: 0.19
 |
 |  bootstrap : bool, default=True
 |      Whether bootstrap samples are used when building trees. If False, the
 |      whole dataset is used to build each tree.
 |
 |  oob_score : bool or callable, default=False
 |      Whether to use out-of-bag samples to estimate the generalization score.
 |      By default, :func:`~sklearn.metrics.accuracy_score` is used.
 |      Provide a callable with signature `metric(y_true, y_pred)` to use a
 |      custom metric. Only available if `bootstrap=True`.
 |
 |      For an illustration of out-of-bag (OOB) error estimation, see the example
 |      :ref:`sphx_glr_auto_examples_ensemble_plot_ensemble_oob.py`.
 |
 |  n_jobs : int, default=None
 |      The number of jobs to run in parallel. :meth:`fit`, :meth:`predict`,
 |      :meth:`decision_path` and :meth:`apply` are all parallelized over the
 |      trees. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`
 |      context. ``-1`` means using all processors. See :term:`Glossary
 |      <n_jobs>` for more details.
 |
 |  random_state : int, RandomState instance or None, default=None
 |      Controls both the randomness of the bootstrapping of the samples used
 |      when building trees (if ``bootstrap=True``) and the sampling of the
 |      features to consider when looking for the best split at each node
 |      (if ``max_features < n_features``).
 |      See :term:`Glossary <random_state>` for details.
 |
 |  verbose : int, default=0
 |      Controls the verbosity when fitting and predicting.
 |
 |  warm_start : bool, default=False
 |      When set to ``True``, reuse the solution of the previous call to fit
 |      and add more estimators to the ensemble, otherwise, just fit a whole
 |      new forest. See :term:`Glossary <warm_start>` and
 |      :ref:`tree_ensemble_warm_start` for details.
 |
 |  class_weight : {"balanced", "balanced_subsample"}, dict or list of dicts,             default=None
 |      Weights associated with classes in the form ``{class_label: weight}``.
 |      If not given, all classes are supposed to have weight one. For
 |      multi-output problems, a list of dicts can be provided in the same
 |      order as the columns of y.
 |
 |      Note that for multioutput (including multilabel) weights should be
 |      defined for each class of every column in its own dict. For example,
 |      for four-class multilabel classification weights should be
 |      [{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of
 |      [{1:1}, {2:5}, {3:1}, {4:1}].
 |
 |      The "balanced" mode uses the values of y to automatically adjust
 |      weights inversely proportional to class frequencies in the input data
 |      as ``n_samples / (n_classes * np.bincount(y))``
 |
 |      The "balanced_subsample" mode is the same as "balanced" except that
 |      weights are computed based on the bootstrap sample for every tree
 |      grown.
 |
 |      For multi-output, the weights of each column of y will be multiplied.
 |
 |      Note that these weights will be multiplied with sample_weight (passed
 |      through the fit method) if sample_weight is specified.
 |
 |  ccp_alpha : non-negative float, default=0.0
 |      Complexity parameter used for Minimal Cost-Complexity Pruning. The
 |      subtree with the largest cost complexity that is smaller than
 |      ``ccp_alpha`` will be chosen. By default, no pruning is performed. See
 |      :ref:`minimal_cost_complexity_pruning` for details. See
 |      :ref:`sphx_glr_auto_examples_tree_plot_cost_complexity_pruning.py`
 |      for an example of such pruning.
 |
 |      .. versionadded:: 0.22
 |
 |  max_samples : int or float, default=None
 |      If bootstrap is True, the number of samples to draw from X
 |      to train each base estimator.
 |
 |      - If None (default), then draw `X.shape[0]` samples.
 |      - If int, then draw `max_samples` samples.
 |      - If float, then draw `max(round(n_samples * max_samples), 1)` samples. Thus,
 |        `max_samples` should be in the interval `(0.0, 1.0]`.
 |
 |      .. versionadded:: 0.22
 |
 |  monotonic_cst : array-like of int of shape (n_features), default=None
 |      Indicates the monotonicity constraint to enforce on each feature.
 |        - 1: monotonic increase
 |        - 0: no constraint
 |        - -1: monotonic decrease
 |
 |      If monotonic_cst is None, no constraints are applied.
 |
 |      Monotonicity constraints are not supported for:
 |        - multiclass classifications (i.e. when `n_classes > 2`),
 |        - multioutput classifications (i.e. when `n_outputs_ > 1`),
 |        - classifications trained on data with missing values.
 |
 |      The constraints hold over the probability of the positive class.
 |
 |      Read more in the :ref:`User Guide <monotonic_cst_gbdt>`.
 |
 |      .. versionadded:: 1.4
 |
 |  Attributes
 |  ----------
 |  estimator_ : :class:`~sklearn.tree.DecisionTreeClassifier`
 |      The child estimator template used to create the collection of fitted
 |      sub-estimators.
 |
 |      .. versionadded:: 1.2
 |         `base_estimator_` was renamed to `estimator_`.
 |
 |  estimators_ : list of DecisionTreeClassifier
 |      The collection of fitted sub-estimators.
 |
 |  classes_ : ndarray of shape (n_classes,) or a list of such arrays
 |      The classes labels (single output problem), or a list of arrays of
 |      class labels (multi-output problem).
 |
 |  n_classes_ : int or list
 |      The number of classes (single output problem), or a list containing the
 |      number of classes for each output (multi-output problem).
 |
 |  n_features_in_ : int
 |      Number of features seen during :term:`fit`.
 |
 |      .. versionadded:: 0.24
 |
 |  feature_names_in_ : ndarray of shape (`n_features_in_`,)
 |      Names of features seen during :term:`fit`. Defined only when `X`
 |      has feature names that are all strings.
 |
 |      .. versionadded:: 1.0
 |
 |  n_outputs_ : int
 |      The number of outputs when ``fit`` is performed.
 |
 |  feature_importances_ : ndarray of shape (n_features,)
 |      The impurity-based feature importances.
 |      The higher, the more important the feature.
 |      The importance of a feature is computed as the (normalized)
 |      total reduction of the criterion brought by that feature.  It is also
 |      known as the Gini importance.
 |
 |      Warning: impurity-based feature importances can be misleading for
 |      high cardinality features (many unique values). See
 |      :func:`sklearn.inspection.permutation_importance` as an alternative.
 |
 |  oob_score_ : float
 |      Score of the training dataset obtained using an out-of-bag estimate.
 |      This attribute exists only when ``oob_score`` is True.
 |
 |  oob_decision_function_ : ndarray of shape (n_samples, n_classes) or             (n_samples, n_classes, n_outputs)
 |      Decision function computed with out-of-bag estimate on the training
 |      set. If n_estimators is small it might be possible that a data point
 |      was never left out during the bootstrap. In this case,
 |      `oob_decision_function_` might contain NaN. This attribute exists
 |      only when ``oob_score`` is True.
 |
 |  estimators_samples_ : list of arrays
 |      The subset of drawn samples (i.e., the in-bag samples) for each base
 |      estimator. Each subset is defined by an array of the indices selected.
 |
 |      .. versionadded:: 1.4
 |
 |  See Also
 |  --------
 |  sklearn.tree.DecisionTreeClassifier : A decision tree classifier.
 |  sklearn.ensemble.ExtraTreesClassifier : Ensemble of extremely randomized
 |      tree classifiers.
 |  sklearn.ensemble.HistGradientBoostingClassifier : A Histogram-based Gradient
 |      Boosting Classification Tree, very fast for big datasets (n_samples >=
 |      10_000).
 |
 |  Notes
 |  -----
 |  The default values for the parameters controlling the size of the trees
 |  (e.g. ``max_depth``, ``min_samples_leaf``, etc.) lead to fully grown and
 |  unpruned trees which can potentially be very large on some data sets. To
 |  reduce memory consumption, the complexity and size of the trees should be
 |  controlled by setting those parameter values.
 |
 |  The features are always randomly permuted at each split. Therefore,
 |  the best found split may vary, even with the same training data,
 |  ``max_features=n_features`` and ``bootstrap=False``, if the improvement
 |  of the criterion is identical for several splits enumerated during the
 |  search of the best split. To obtain a deterministic behaviour during
 |  fitting, ``random_state`` has to be fixed.
 |
 |  References
 |  ----------
 |  .. [1] :doi:`L. Breiman, "Random Forests", Machine Learning, 45(1), 5-32, 2001.
 |         <10.1023/A:1010933404324>`
 |
 |  Examples
 |  --------
 |  >>> from sklearn.ensemble import RandomForestClassifier
 |  >>> from sklearn.datasets import make_classification
 |  >>> X, y = make_classification(n_samples=1000, n_features=4,
 |  ...                            n_informative=2, n_redundant=0,
 |  ...                            random_state=0, shuffle=False)
 |  >>> clf = RandomForestClassifier(max_depth=2, random_state=0)
 |  >>> clf.fit(X, y)
 |  RandomForestClassifier(...)
 |  >>> print(clf.predict([[0, 0, 0, 0]]))
 |  [1]
 |
 |  Method resolution order:
 |      RandomForestClassifier
 |      ForestClassifier
 |      sklearn.base.ClassifierMixin
 |      BaseForest
 |      sklearn.base.MultiOutputMixin
 |      sklearn.ensemble._base.BaseEnsemble
 |      sklearn.base.MetaEstimatorMixin
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._repr_html.base.ReprHTMLMixin
 |      sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, n_estimators=100, *, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='sqrt', max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None, monotonic_cst=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  set_fit_request(self: sklearn.ensemble._forest.RandomForestClassifier, *, sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.ensemble._forest.RandomForestClassifier
 |      Configure whether metadata should be requested to be passed to the ``fit`` method.
 |
 |      Note that this method is only relevant when this estimator is used as a
 |      sub-estimator within a :term:`meta-estimator` and metadata routing is enabled
 |      with ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please check the :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``fit`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``fit``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |      existing request. This allows you to change the request for some
 |      parameters and not others.
 |
 |      .. versionadded:: 1.3
 |
 |      Parameters
 |      ----------
 |      sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |          Metadata routing for ``sample_weight`` parameter in ``fit``.
 |
 |      Returns
 |      -------
 |      self : object
 |          The updated object.
 |
 |  set_score_request(self: sklearn.ensemble._forest.RandomForestClassifier, *, sample_weight: Union[bool, NoneType, str] = '$UNCHANGED$') -> sklearn.ensemble._forest.RandomForestClassifier
 |      Configure whether metadata should be requested to be passed to the ``score`` method.
 |
 |      Note that this method is only relevant when this estimator is used as a
 |      sub-estimator within a :term:`meta-estimator` and metadata routing is enabled
 |      with ``enable_metadata_routing=True`` (see :func:`sklearn.set_config`).
 |      Please check the :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      The options for each parameter are:
 |
 |      - ``True``: metadata is requested, and passed to ``score`` if provided. The request is ignored if metadata is not provided.
 |
 |      - ``False``: metadata is not requested and the meta-estimator will not pass it to ``score``.
 |
 |      - ``None``: metadata is not requested, and the meta-estimator will raise an error if the user provides it.
 |
 |      - ``str``: metadata should be passed to the meta-estimator with this given alias instead of the original name.
 |
 |      The default (``sklearn.utils.metadata_routing.UNCHANGED``) retains the
 |      existing request. This allows you to change the request for some
 |      parameters and not others.
 |
 |      .. versionadded:: 1.3
 |
 |      Parameters
 |      ----------
 |      sample_weight : str, True, False, or None,                     default=sklearn.utils.metadata_routing.UNCHANGED
 |          Metadata routing for ``sample_weight`` parameter in ``score``.
 |
 |      Returns
 |      -------
 |      self : object
 |          The updated object.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  __annotations__ = {'_parameter_constraints': <class 'dict'>}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from ForestClassifier:
 |
 |  __sklearn_tags__(self)
 |
 |  predict(self, X)

## Hiperparámetros

In [26]:
rf_grid = dict(
    rf__ccp_alpha= [0.01, 0.03],
    rf__n_estimators= [50, 100],
    rf__max_features= [5, 8]  # En Python sí hacemos OHE
)

**rf__ccp_alpha**: Este hiperparámetro corresponde al parámetro de complejidad (Cost-Complexity Pruning, CCP) para el Random Forest. Es la penalización aplicada a la complejidad de cada árbol en el bosque. Un valor más alto de ccp_alpha generará árboles más pequeños y menos complejos, ayudando a prevenir el sobreajuste. En tu lista, estás probando con valores de 0.01 y 0.03.

**rf__n_estimators**: Este hiperparámetro especifica el número de árboles en el bosque. Un mayor número de árboles generalmente mejora la robustez y la capacidad de generalización del modelo, pero también puede aumentar el costo computacional. En tu lista, estás probando con 50 y 100 árboles.

**rf__max_features**: Este hiperparámetro controla la cantidad máxima de características que se deben considerar al dividir un nodo. Puede ser un número fijo o un porcentaje del total de características. Limitar el número de características puede ayudar a prevenir el sobreajuste

##TUNNING

In [27]:
rf_tuned = GridSearchCV( rf_pipe, rf_grid, cv=cv, n_jobs=-1)

In [28]:
rf_tuned.fit( X_train, y_train)

GridSearchCV(cv=RepeatedStratifiedKFold(n_repeats=2, n_splits=5, random_state=123),
             estimator=Pipeline(steps=[('preproc',
                                        ColumnTransformer(transformers=[('encoder',
                                                                         OneHotEncoder(),
                                                                         ['Geography',
                                                                          'IsActiveMember']),
                                                                        ('scaler',
                                                                         StandardScaler(),
                                                                         ['Age',
                                                                          'Balance',
                                                                          'NumOfProducts'])])),
                                       ('rf',
                                        RandomForestClassifier(class_weight='balanced',
                                                               random_state=123))]),
             n_jobs=-1,
             param_grid={'rf__ccp_alpha': [0.01, 0.03],
                         'rf__max_features': [5, 8],
                         'rf__n_estimators': [50, 100]})

In [29]:
rf_tuned.best_estimator_

Pipeline(steps=[('preproc',
                 ColumnTransformer(transformers=[('encoder', OneHotEncoder(),
                                                  ['Geography',
                                                   'IsActiveMember']),
                                                 ('scaler', StandardScaler(),
                                                  ['Age', 'Balance',
                                                   'NumOfProducts'])])),
                ('rf',
                 RandomForestClassifier(ccp_alpha=0.01, class_weight='balanced',
                                        max_features=5, random_state=123))])

##Acurracy

In [30]:
acurracyRF_TunnedTrain= metrics.accuracy_score(y_train, rf_tuned.predict(X_train))
acurracyRF_TunnedTrain

0.778125

In [31]:
acurracyRF_tunedTest= metrics.accuracy_score(y_test, rf_tuned.predict(X_test))
acurracyRF_tunedTest

0.7865

##Precission and Recall

## Train

In [32]:
print( classification_report(y_train, rf_tuned.predict(X_train)) )

              precision    recall  f1-score   support

           0       0.91      0.80      0.85      6370
           1       0.47      0.69      0.56      1630

    accuracy                           0.78      8000
   macro avg       0.69      0.74      0.70      8000
weighted avg       0.82      0.78      0.79      8000

In [33]:
from sklearn.metrics import recall_score
recallRF_bal_tunedtrain = recall_score( y_train, rf_tuned.predict(X_train), average=None )
recallRF_bal_tunedtrain

recallRF_bal_tunedtrainYes = recallRF_bal_tunedtrain[1]
recallRF_bal_tunedtrainYes

np.float64(0.6858895705521473)

In [34]:
from sklearn.metrics import precision_score
precisionRF_bal_tunedTrain = precision_score( y_train,  rf_tuned.predict(X_train), average=None )
precisionRF_bal_tunedTrain

precisionRF_bal_tunedTrainYes = precisionRF_bal_tunedTrain[1]
precisionRF_bal_tunedTrainYes

np.float64(0.46955060898782025)

## Test

In [35]:
print( classification_report( y_test,  rf_tuned.predict(X_test) ))

              precision    recall  f1-score   support

           0       0.92      0.80      0.86      1593
           1       0.48      0.72      0.58       407

    accuracy                           0.79      2000
   macro avg       0.70      0.76      0.72      2000
weighted avg       0.83      0.79      0.80      2000

In [36]:
from sklearn.metrics import recall_score
recallRF_bal_tunedTest = recall_score( y_test, rf_tuned.predict(X_test), average=None )
recallRF_bal_tunedTest

recallRF_bal_tunedTestYes = recallRF_bal_tunedTest[1]
recallRF_bal_tunedTestYes

np.float64(0.7199017199017199)

In [37]:
from sklearn.metrics import precision_score
precisionRF_bal_tunedTest = precision_score( y_test,  rf_tuned.predict(X_test), average=None )
precisionRF_bal_tunedTest

precisionRF_bal_tunedTestYes = precisionRF_bal_tunedTest[1]
precisionRF_bal_tunedTestYes

np.float64(0.4834983498349835)

##AUC-TEST

In [38]:
y_test_probabilities = rf_tuned.predict_proba(X_test)
y_test_probabilities # columna 0; columna 1

array([[0.60643659, 0.39356341],
       [0.79188499, 0.20811501],
       [0.81657907, 0.18342093],
       ...,
       [0.74371533, 0.25628467],
       [0.78303108, 0.21696892],
       [0.33932234, 0.66067766]], shape=(2000, 2))

In [39]:
#                        predict                                      predict
#                     no         yes                               no      yes
#real         no                                  real        no    TN      FP
#             yes                                             yes   FN      TP

y_test_proba =  rf_tuned.predict_proba(X_test)[::,1]  # Escogemos 1 porque nos interesa el valor de YES: guiarse de la M. Confusion

auc_test_RF_bal_tuned = metrics.roc_auc_score(y_test,y_test_proba)

print( auc_test_RF_bal_tuned )

0.8412380022549514

##AUC-TRAIN

In [40]:
y_train_probabilities = rf_tuned.predict_proba(X_test)
y_train_probabilities

array([[0.60643659, 0.39356341],
       [0.79188499, 0.20811501],
       [0.81657907, 0.18342093],
       ...,
       [0.74371533, 0.25628467],
       [0.78303108, 0.21696892],
       [0.33932234, 0.66067766]], shape=(2000, 2))

In [41]:
#                        predict                                      predict
#                     no         yes                               no      yes
#real         no                                  real        no    TN      FP
#             yes                                             yes   FN      TP

y_train_proba =  rf_tuned.predict_proba(X_train)[::,1]  # Escogemos 1 porque nos interesa el valor de YES: guiarse de la M. Confusion

auc_train_RF_bal_tuned = metrics.roc_auc_score(y_train, y_train_proba )

print( auc_train_RF_bal_tuned )

0.83115765041269

##Matrices de Confusion

In [42]:
probs = rf_tuned.predict(X_train)                            #X_train
confusion_matrix2 = pd.crosstab( y_train ,probs,)  # reales, predichos SEGUN Python
confusion_matrix2

col_0      0     1
Exited
0       5107  1263
1        512  1118

In [43]:
probs = rf_tuned.predict(X_test)                            #X_test
confusion_matrix2 = pd.crosstab( y_test ,probs,)  # reales, predichos SEGUN Python
confusion_matrix2

col_0      0    1
Exited
0       1280  313
1        114  293

#Guardando el modelo

In [44]:
import joblib

# Guardar el modelo
joblib.dump( rf_tuned,'E:/OAZ/INEI CURSOS2025 ACT/ENEI 2026 actualizado/04 ML EN PRODUCCION/G1/04 Clasificacion_caso/modelo_rfchurn_tunning.joblib')

['E:/OAZ/INEI CURSOS2025 ACT/ENEI 2026 actualizado/04 ML EN PRODUCCION/G1/04 Clasificacion_caso/modelo_rfchurn_tunning.joblib']

In [45]:
# Cargar el modelo
loaded_model = joblib.load('E:/OAZ/INEI CURSOS2025 ACT/ENEI 2026 actualizado/04 ML EN PRODUCCION/G1/04 Clasificacion_caso/modelo_rfchurn_tunning.joblib')

#DESPLIEGUE

In [46]:
import numpy as np
import pandas as pd
path_base = 'E:/OAZ/INEI CURSOS2025 ACT/ENEI 2026 actualizado/04 ML EN PRODUCCION/G1/04 Clasificacion_caso/'
data= pd.read_csv(f'{path_base}/datanueva.csv', sep = ',')
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,196,15594815,Aleshire,807,France,Male,35,3,174790.15,1,1,1,600.36,0
1,207,15755262,McDonald,608,Spain,Female,41,3,89763.84,1,0,0,199304.74,1
2,218,15786308,Millar,730,Spain,Female,33,9,0.00,2,0,0,176576.62,0
3,219,15659366,Shih,807,France,Male,43,1,105799.32,2,1,0,34888.04,1
4,233,15787174,Sergeyev,512,France,Female,37,1,0.00,2,0,1,156105.03,0
5,539,15794142,Ferreira,564,Germany,Female,62,5,114931.35,3,0,1,18260.98,1
6,941,15754084,Palazzi,710,Spain,Male,35,1,106518.52,1,1,1,127951.81,0
7,943,15804586,Lin,376,France,Female,46,6,0.00,1,1,0,157333.69,1
8,3130,15694453,Walker,631,Germany,Male,37,9,131519.49,2,1,1,51752.18,0
9,3131,15813113,Chang,795,Spain,Female,56,5,0.00,1,1,0,35418.69,1
10,3132,15614187,Pottinger,648,Germany,Female,39,3,126935.98,2,0,1,57995.74,0

In [47]:
##Seleccinamos las variables por la selección hecha: RFA
# A pesar de no ser selecionado consideraremos a Geography                          Target
dataf=data[[ "Geography", 'Age',  'Balance', 'NumOfProducts', 'IsActiveMember' ,  'Exited' ]]
dataf

   Geography  Age    Balance  NumOfProducts  IsActiveMember  Exited
0     France   35  174790.15              1               1       0
1      Spain   41   89763.84              1               0       1
2      Spain   33       0.00              2               0       0
3     France   43  105799.32              2               0       1
4     France   37       0.00              2               1       0
5    Germany   62  114931.35              3               1       1
6      Spain   35  106518.52              1               1       0
7     France   46       0.00              1               0       1
8    Germany   37  131519.49              2               1       0
9      Spain   56       0.00              1               0       1
10   Germany   39  126935.98              2               1       0

# Cargar el modelo

In [48]:
probs = loaded_model.predict(dataf)
probs

import pandas as pd
# Create the dataframe
df = pd.DataFrame(probs)
df

    0
0   0
1   0
2   0
3   1
4   0
5   1
6   0
7   1
8   0
9   1
10  0

In [49]:
probs2 =  loaded_model.predict_proba(dataf)
probs2

array([[0.64770883, 0.35229117],
       [0.5073451 , 0.4926549 ],
       [0.81183666, 0.18816334],
       [0.36480485, 0.63519515],
       [0.81657907, 0.18342093],
       [0.26948107, 0.73051893],
       [0.64770883, 0.35229117],
       [0.19768669, 0.80231331],
       [0.74165958, 0.25834042],
       [0.19768669, 0.80231331],
       [0.71731761, 0.28268239]])

In [50]:
probs2_df = pd.DataFrame(probs2, columns=["Prob_0", "Prob_1"])
probs2_df

      Prob_0    Prob_1
0   0.647709  0.352291
1   0.507345  0.492655
2   0.811837  0.188163
3   0.364805  0.635195
4   0.816579  0.183421
5   0.269481  0.730519
6   0.647709  0.352291
7   0.197687  0.802313
8   0.741660  0.258340
9   0.197687  0.802313
10  0.717318  0.282682

In [51]:
# Concatenar 'df' y 'probs_df' a lo largo de las columnas (axis=1)
result_df = pd.concat([df, probs2_df], axis=1)
result_df

    0    Prob_0    Prob_1
0   0  0.647709  0.352291
1   0  0.507345  0.492655
2   0  0.811837  0.188163
3   1  0.364805  0.635195
4   0  0.816579  0.183421
5   1  0.269481  0.730519
6   0  0.647709  0.352291
7   1  0.197687  0.802313
8   0  0.741660  0.258340
9   1  0.197687  0.802313
10  0  0.717318  0.282682

In [52]:
# Renombrar la columna '0' a 'Predicción'
result_df.rename(columns={0: 'Predicción'}, inplace=True)
result_df

    Predicción    Prob_0    Prob_1
0            0  0.647709  0.352291
1            0  0.507345  0.492655
2            0  0.811837  0.188163
3            1  0.364805  0.635195
4            0  0.816579  0.183421
5            1  0.269481  0.730519
6            0  0.647709  0.352291
7            1  0.197687  0.802313
8            0  0.741660  0.258340
9            1  0.197687  0.802313
10           0  0.717318  0.282682

##Variables Filtradas y probablidades

In [53]:
resultados = pd.concat([dataf , result_df], axis=1)
resultados

#Exited no estaría en un modelo en producción

,Geography,Age,Balance,NumOfProducts,IsActiveMember,Exited,Predicción,Prob_0,Prob_1
0,France,35,174790.15,1,1,0,0,0.647709,0.352291
1,Spain,41,89763.84,1,0,1,0,0.507345,0.492655
2,Spain,33,0.00,2,0,0,0,0.811837,0.188163
3,France,43,105799.32,2,0,1,1,0.364805,0.635195
4,France,37,0.00,2,1,0,0,0.816579,0.183421
5,Germany,62,114931.35,3,1,1,1,0.269481,0.730519
6,Spain,35,106518.52,1,1,0,0,0.647709,0.352291
7,France,46,0.00,1,0,1,1,0.197687,0.802313
8,Germany,37,131519.49,2,1,0,0,0.741660,0.258340
9,Spain,56,0.00,1,0,1,1,0.197687,0.802313
10,Germany,39,126935.98,2,1,0,0,0.717318,0.282682